### ISSUE TITLE
Check whether we should do exit after exec on Linux

### ISSUE THREAD

**Issue by alkurbatov** [alkurbatov/cpp-sc2#22]
Seems that the code which starts game client on Linux/OS X is wrong as it doesn't do exit in the forked process.

**Comment by yanntm** [comment]
either exec is succesful and you swap your current process image to go execute that, and *will not ever* come back.
In other words, per the manual, 
"
The exec() functions only return if an error has occurred. The return value is -1, and errno is set to indicate the error.
"
https://linux.die.net/man/3/exec

**Comment by alkurbatov** [comment]
Thats why I wanted to check it first in the debugger first.
Here it is:
https://github.com/alkurbatov/cpp-sc2/blob/b628ca955324a00cb18eeb7958dc08a35d1258bb/src/sc2utils/sc2_manage_process.cc#L404

**Comment by yanntm** [comment]
looking at the code, the main issue is it's creating zombie processes, there is no call to "wait/waitpid" at all. After sending a kill signal to the child, we would normally wait for it to actually die with a call to waitpid, probably this would go well in the "removePid" function, that is tracking what children we have at a given point. And I confirm that sleep in the code is bogus dead code.

**Comment by alkurbatov** [comment]
Yep, they kill every child later. Pretty weird approach, might be some reason behind it. This sleep 1000 may be needed to force the child die before it goes further :)

**Comment by yanntm** [comment]
so a first patch is to drop the sleep that is dead code, and add after https://github.com/alkurbatov/cpp-sc2/blob/b628ca955324a00cb18eeb7958dc08a35d1258bb/src/sc2utils/sc2_manage_process.cc#L273 a call to`int status; waitpid(pid,nullptr,0)` + perror/strerror/errno if it fails
https://linux.die.net/man/2/waitpid

**Comment by alkurbatov** [comment]
If I not mistaken, they intentionally avoided waitpid cause they start several game clients. It is not that simple, unfortunately.

**Comment by yanntm** [comment]
waitpid with a first argument waits for precisely that child process to end, so there is no issue here, we do have the child pid which we stored just after the successful fork call.

**Comment by alkurbatov** [comment]
Having said that I meant that it 90% will not work if I just add `waitpid` to the code due to the internal implementation of the API. They might try to wait pid somewhere, but not in the place where child is born. So, the issue requires some investigation.

**Comment by yanntm** [comment]
well the wait call is there for windows (or it's equivalent) in terminate process
https://github.com/alkurbatov/cpp-sc2/blob/b628ca955324a00cb18eeb7958dc08a35d1258bb/src/sc2utils/sc2_manage_process.cc#L244

but a search in the repo shows no other hits, so the linux version maybe they just hacked pretty fast

**Comment by alkurbatov** [comment]
Fixed in a very simple way.

**Comment by yanntm** [comment]
The exit you placed after execve is still dead code (just like the sleep was). 

This also does not solve the missing call to wait/waitpid in terminate process.

**Comment by alkurbatov** [comment]
@yanntm it is not dead because the pid is passed outside of this function. So this exit (as well as sleep) is necessary. This commit fixes exactly what I wanted to fix and what was described in the issue.
As for missing waitpid, I don't see why it is necessary in such implementation.

**Comment by yanntm** [comment]
Ok, nvm, I'll submit a patch with the wait added a bit later when I get the time to format it properly it's a detail really, but fork=>wait is like malloc=>free. Since we noticed the missing call, might as well fix it.

The pid comes from fork, above the exec, either exec succeeds and the process is gone or we get -1 and hit the exit call of line 408 https://github.com/alkurbatov/cpp-sc2/commit/9b10fc0f21f3398848a152a2ed54b89538281438#diff-351145669102b6e45f3d20054047de40L408
Again this sleep/exit does not change program behavior so it's not important (it is just unreachable instructions).

**Comment by alkurbatov** [comment]
`but fork=>wait is like malloc=>free`
I know, but waitpid blocks the main thread and if I understood the code properly, they don't want this function to be blocking. Thats why they use a separate vector to store pics and manage the processes later.
